language: cpp

compiler:
  - gcc

sudo: false

addons:
    apt:
        packages:
        - cmake

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda config --add channels http://conda.binstar.org/omnia
  - conda create --yes -n py3 python=3.6
  - source activate py3
  - conda install --yes openmm=7.2 swig

install:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - make install
  - make PythonInstall

script:
  - make test
